### ISSUE TITLE
Vac-able? 

### ISSUE THREAD

**Issue by suciuale** [thehen101/Sublime#1]
Is it undetected?

**Comment by ghost** [comment]
This is a public cheat. It is recommended to take the code and make it your own by changing it thus making it harder/impossible to detect.
If you do wish to use the code in its vanilla state as of the current date (11/08/17) the cheat is undetected.
Please understand that you are liable if you get banned in any way shape or form.

Happy cheating :^)

**Comment by thehen101** [comment]
The response above is quite accurate. As of 05/10/2017 (today), this cheat is VAC undetected and it has been that way since this repository was created. Closing.
